default:
  tags:
    - poc

.tests:
  script:
    - bundle exec rake
    -  if [ -z "$SKIP_BENCHMARK" ]; then bundle exec rake benchmarks; fi;

default:
  before_script:
    - gem install bundler --no-document
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"

ruby_2_2:
  extends: .tests
  before_script:
    - gem install bundler -v 1.17.3 --no-document
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  image: ruby:2.2
  variables:
    SKIP_BENCHMARK: 'true'

ruby_2_3:
  extends: .tests
  image: ruby:2.3

ruby_2_4:
  extends: .tests
  image: ruby:2.4

ruby_2_5:
  extends: .tests
  image: ruby:2.5
